# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-3700d08d-0bb0-4610-bc4d-4e41ce0f0ec4";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-3700d08d-0bb0-4610-bc4d-4e41ce0f0ec4".device = "/dev/disk/by-uuid/3700d08d-0bb0-4610-bc4d-4e41ce0f0ec4";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-3700d08d-0bb0-4610-bc4d-4e41ce0f0ec4";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-3700d08d-0bb0-4610-bc4d-4e41ce0f0ec4";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2917-8DF5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/d4379bd5-954e-458e-87ba-eaa1da6ce41c";
      randomEncryption.enable = true;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
