# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-483ef956-d9c2-4d75-8ce1-f5604d6b071b";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices = {
    "luks-483ef956-d9c2-4d75-8ce1-f5604d6b071b".device =
      "/dev/disk/by-uuid/483ef956-d9c2-4d75-8ce1-f5604d6b071b";
    "luks-7c9eacbe-4d01-4ce7-8d6a-4b0764705e9a".device =
      "/dev/disk/by-uuid/7c9eacbe-4d01-4ce7-8d6a-4b0764705e9a";
  };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-483ef956-d9c2-4d75-8ce1-f5604d6b071b";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-483ef956-d9c2-4d75-8ce1-f5604d6b071b";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B3CA-9CAB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-7c9eacbe-4d01-4ce7-8d6a-4b0764705e9a"; }
  ];

  boot.resumeDevice = "/dev/mapper/luks-7c9eacbe-4d01-4ce7-8d6a-4b0764705e9a";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
